# https://github.com/marketplace/actions/merge-pull-requests-automerge-action

name: automerge
on:
  pull_request:
    types:
      - labeled
      - opened
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: automerge
        name: Merge pull requests (automerge-action)
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.DEPLOY_BOT_TOKEN }}"
          UPDATE_METHOD: "squash"
          MERGE_LABELS: "${{ vars.AUTOMERGE_LABELS }}"
